# Generated by Django 3.2 on 2021-04-14 22:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmorterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmorterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('SA', 'Shop Admin'), ('C', 'Customer'), ('SO', 'Shop Owner'), ('WA', 'Web Admin')], help_text='Select allowed PERMISSION type', max_length=15)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmorterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('groups', models.ManyToManyField(to='eshop.SmorterGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='smortergroup',
            name='permissions',
            field=models.ManyToManyField(to='eshop.SmorterPermission'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 4, 15, 0, 32, 9, 132805))),
                ('admin_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.smortergroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.smorteruser')),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
    ]
