# Generated by Django 3.2 on 2021-04-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_auto_20210415_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='specs',
            field=models.CharField(default={}, max_length=1000),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(default={}, max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.smorteruser')),
                ('items', models.ManyToManyField(to='eshop.Item')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.paymentmethod')),
                ('shipment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.shipmentmethod')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.shop')),
            ],
            options={
                'ordering': ['customer', 'shop'],
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='payment_methods',
            field=models.ManyToManyField(to='eshop.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shipment_methods',
            field=models.ManyToManyField(to='eshop.ShipmentMethod'),
        ),
    ]
