# Generated by Django 3.2 on 2021-04-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_auto_20210416_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WP', 'Waiting for payment'), ('OA', 'Order accepted'), ('WS', 'Waiting to be shipped'), ('WD', 'Waiting for delivery'), ('AC', 'Arrival confirmed')], default='WP', max_length=15),
        ),
    ]
