# Generated by Django 3.2 on 2021-05-12 17:14

from django.db import migrations, models
import eshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop.models.shop_img_path),
        ),
    ]
