# Generated by Django 3.2 on 2021-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0018_alter_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
