# Generated by Django 3.2.4 on 2021-06-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0019_alter_shop_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='admin_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.smortergroup'),
        ),
    ]
