# Generated by Django 3.2 on 2021-06-20 19:59

from django.db import migrations, models
import eshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0020_alter_shop_admin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='image_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to=eshop.models.item_img_path, width_field='image_width'),
        ),
    ]
