# Generated by Django 3.2 on 2021-06-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0022_auto_20210620_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='eshop.OrderedItem'),
        ),
    ]
