# Generated by Django 3.2 on 2021-06-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0023_alter_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='eshop.OrderedItem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eshop.smorteruser')),
            ],
        ),
    ]
