# Generated by Django 3.2 on 2021-06-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0024_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='eshop.OrderedItem'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.item'),
        ),
    ]
