# Generated by Django 3.2 on 2021-06-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0026_ordereditem_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='specs',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
